.. _01_pagelink_main:

I stumbled on reStructureText while I am browsing on this blog, https://linuxtools-rst.readthedocs.io/zh_CN/latest/base/01_use_man.html, on Linux note.  
I am still not sure about reST's syntax as I am getting used to MarkDown language.  Anyway, it's good to learn.





Heading 1
==========

Heading 2 : ...
--------------------
blah...blah.. content...

- List Item 1
- List Item 2
- List Item 3

下面介紹這些命令；

Heading 2 : ...
--------------------

Heading 3 : 
^^^^^^^^^^^^^^^^^^^^  
